/* Auto-generated by AuthSystem - 2026-03-03T04:12:43.632Z */
// Public configuration for auth forms
// These values are embedded at build time
// The forms call the public API (Netlify Functions), not Supabase directly

export const config = {
  apiBaseUrl: '/api', // Uses Netlify redirect from netlify.toml
  appId: 'app_b9b5f22b-cda',
  apiKey: 'ak_production_9c9c978d807990ca3d43c195a608d3eb'
};
