/* Auto-generated by AuthSystem - 2026-03-03T04:44:08.507Z */
// Public configuration for auth forms
// These values are embedded at build time
// The forms call the public API (Netlify Functions), not Supabase directly

export const config = {
  apiBaseUrl: '/api', // Uses Netlify redirect from netlify.toml
  appId: 'app_b9b5f22b-cda',
  apiKey: 'ak_production_01b4135050c08a6d177c87a73c17fe06'
};
