/* Auto-generated by AuthSystem - 2026-03-03T04:52:47.825Z */
// Public configuration for auth forms
// These values are embedded at build time
// The forms call the public API (Netlify Functions), not Supabase directly

export const config = {
  apiBaseUrl: '/api', // Uses Netlify redirect from netlify.toml
  appId: 'app_b9b5f22b-cda',
  apiKey: 'ak_production_6f4951a34b34d131a03659317dfb12b6'
};
